### ISSUE TITLE
ICC Profile for BOE NV133FHM-N52

### ISSUE THREAD

**Issue by maxadamski** [tlvince/xiaomi-mi-notebook-air-13#2]
I found a color profile for the Mi Notebook Air with the BOE NV133FHM-N52 screen. My screen looks much better after applying, as the profile gets rid of the yellow tint. [Here](https://framagit.org/solus-fr/xiaomi13solus/-/blob/573f076645d3a3879b465510fcd4061f599277c8/NV133FHM-N52%20%231%202018-03-05%2010-23%202.2%20F-S%20XYZLUT+MTX.icc) is the ICC file. I'm not the author, but could link it in the README, so people coming from Arch Wiki can find it easily?

**Comment by tlvince** [comment]
Sounds good to me! Perhaps you could ask the author for permission for us to mirror it here, or otherwise, linking to it as you mentioned would be fine.

**Comment by tlvince** [comment]
Closed by #3
